s=[1,2.2,object,"TMI"]
print(type(s))
print("0-index:",s[0])
print("oxirgi index:",s[-1])
print(s[1:])
s[1]='amaliy'
s=[1]*10
print(s)
s=list(range(10))
print(s)
s=list(range(5,10))
print(s)
s=list(range(5,10,2))
print(s)
for s1 in s:
    print(s1)
s.append("Amaliy matematika")
print(s)
s.insert(2,"TMI")
print(s)
i=s.index(5)
print(i)
l=s.pop(i)
print(l)
print(s)
s.reverse()
print(s)
s=['Amaliy','Matematika','TMI']
print(max(s))
print(min(s))
ismlar=["Anvar","Sobir","Qosim"]
ismlar_soni=ismlar.count("Sobir")
print(ismlar_soni)
ismlar.sort()
print(ismlar)
v1=["Toshkent","Xorazm","Buxoro","Navoi","Jizzax"]
v2=v1[:2]
print(v2)
v2=v1[2:4]
print(v2)
v3=v1[1:5:2]
print(v3)
xodimlar=[
["Tolib",33],
["Akmal",30],
["Botir",27]]
print(xodimlar[0])
print(xodimlar[1][0])
print(xodimlar[2][1])